server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/zzuni_story?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: "3242189"

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  loggin:
    level:
      org.hibernate:
        type.descriptor.sql: trace
        SQL: DEBUG